### PR TITLE
Fixes comma placement, removes redundant anchor

### PR DESCRIPTION
**Pull request by colinta**
Also, having leading, trailing, _and_ centerX seems redundant.

Love the syntax - how about updating constraints w/ animation?

### CODE REVIEW

**Comment by mergesort** [comment]
Thanks @colinta! Will merge this in, just overlooked that.

What ideas do you have for animations? Historically if I want to animate something, I retain the constraint and follow the standard UIKit mechanisms for doing that. Do you have another idea for doing it?

**Comment by colinta** [comment]
That's what I was wondering - where are the native (or wrapped) constraint objects, so that the `constant` prop can be updated.

**Comment by mergesort** [comment]
Each of the methods returns an `[NSLayoutConstraint]`, except for `pinEdge` which returns an `NSLayoutConstraint`. That's the same technique as `NSLayoutAnchor`, so anywhere you do that with `NSLayoutAnchor`, you should be able to do it here.

**Comment by colinta** [comment]
Ahh gotcha 👍

**Pull request merged**
